### ISSUE TITLE
Improve details given in the README.md ?

### ISSUE THREAD

**Issue by Naereen** [steindoringi/MetaLearningGP#2]
Hi!

The `README.md` document is quite short, maybe it could be improved by adding more details:
- [x] a short introduction on what is the domain, task, method, etc, implemented here,
- [x] details regarding what are the test data, where they came from (are they free and open? are they included? should they be downloaded before running the training & testing?)
- [x] more details regarding the dependencies, a [`requirements.txt`](https://pip.readthedocs.io/en/1.1/requirements.html) file should be added, so users can easily [install the requirements](https://pip.pypa.io/en/stable/user_guide/?highlight=requirements#id1) or test your project in a virtualenv,
- [x] exact command that someone can copy and paste to launch the training & testing, and reproduce your results.

I can (try to) help, if you need/want. Thanks in advance!

**Comment by steindoringi** [comment]
Thanks for the feedback Naereen! I've updated the code to include the RL experiments from the paper and updated the readme.
