### ISSUE TITLE
error running generate_toy_data

### ISSUE THREAD

**Issue by xinleipan** [steindoringi/MetaLearningGP#4]
I can't run this function: generate_toy_data. Some incompatibility with array dimensions. Could you fix that? Maybe a typo. When I run generate_toy_daat(1,7,100), it returns with value error: operands could not be broadcast together with shapes (39,) (100,)

**Comment by steindoringi** [comment]
You're right xinleipan, the toy dataset was hard coded just to demonstrate the basic properties of the model. There is a more complete version of the code up now.
